### ISSUE TITLE
Exponents with decimals evaluate to 0.00

### ISSUE THREAD

**Issue by gyoder** [CalcVox/evox#2]
Any exponent with a decimal either in the power or the base evaluates to 0. 
Tested on CalcVox

Evaluates correctly:
2 ^ 2
5 ^ 2
(5-2) ^ 3

Broken:
2.1 ^ 2
4 ^ 0.5
64 ^ (1/3)
2.0 ^ 2

**Comment by trypsynth** [comment]
It seems the decimal fixes in #1 completely fixed all of these, at least for me. @Gyoder, Do you mind testing again?
