### ISSUE TITLE
Mismatched parentheses evaluate to 0.00

### ISSUE THREAD

**Issue by gyoder** [CalcVox/evox#3]
If there are parentheses that do not close, it will evaluate to 0 no matter the function
Tested on CalcVox

Tested to Evaluate to 0.00
2 * (1+2
2 + (1

**Comment by gyoder** [comment]
May want to have a separate mode for interpreting malformed parentheses or throw an error.

**Comment by trypsynth** [comment]
Fixed; a C++ exception is now thrown with an informative error message. The application can handle it however they wish.
