### ISSUE TITLE
Fix building with platformio

### ISSUE THREAD

**Issue by trypsynth** [CalcVox/evox#9]
For some reason, including this library in a platformio project tries to build the tester. Wonder if it's setting all option to ON by default?

**Comment by gyoder** [comment]
@TheQuinbox I am on my phone right now but the export is only for packing the repo. Check out the following I think it will solve the issue

https://docs.platformio.org/en/latest/manifests/library-json/fields/build/includedir.html

https://docs.platformio.org/en/latest/manifests/library-json/fields/build/srcfilter.html

**Comment by trypsynth** [comment]
@gyoder, I've added it. I can't test if it works quite yet, but I will soon, or you can if you want.
